name: edit_distance
description: Implementation of string distance algorithms.
version: 0.3.0
author: Kwang Yul Seo <email@example.com>
homepage: https://github.com/kseo/edit_distance

environment:
  sdk: '>=2.0.0-dev.61 <3.0.0'

dependencies:
  quiver: ^2.0.1

dev_dependencies:
  test: '>=1.2.0 <2.0.0'
